activation_mode: tanh
adaptive_control: false
adaptive_control_interval: 20
albedo_activation_mode: tanh
albedo_init: 0.1
anisotropy_threshold: 15.0
aug_noise_std_camera: 0.0
aug_noise_std_camera_norm: 0.0
aug_noise_std_laser: 0.0
aug_noise_std_laser_norm: 0.0
batch_size: 1
batch_size_initial: 1
dT: 3.2e-11
device: cuda:0
gamma: 0.8
grad_threshold: 0.0003
init_spatial_fraction: 1.0
isconfocal: false
isplanar: true
isretroreflective: false
lambda_albedo_bimodal: 0.0
lambda_albedo_sparsity: 0.0
lambda_albedo_uniformity: 0.0
lambda_loss_variance: 0.0
lambda_neighbor_consistency: 0.0
lambda_scale_anisotropy: 0.0
lambda_spatial_clustering: 0.0
lambda_spatial_tiling: 0.0
laser_norm_start_epoch: 0
log_interval: 1
lr_albedo: 0.05
lr_albedo_post_norm: 3.0e-05
lr_albedo_reconfig: 1.0e-05
lr_quat: 0.01
lr_quat_post_norm: 0.0008
lr_quat_reconfig: 5.0e-05
lr_scale: 0.01
lr_scale_post_norm: 0.0008
lr_scale_reconfig: 5.0e-05
lr_schedule: multistep
lr_xy: 0.005
lr_xy_post_norm: 0.0005
lr_xy_reconfig: 3.0e-05
lr_z: 0.003
lr_z_post_norm: 0.0001
lr_z_reconfig: 5.0e-05
mat_path: ./real_data/real_trans_dataset_Swall3_E_32ps_manualz0_center.mat
milestones:
- 800
- 1600
min_lr_scale: 0.001
min_opacity: 0.05
norm_cycle_off_batch: 1
norm_cycle_off_len: 0
norm_cycle_on_batch: 1
norm_cycle_on_len: 1000
num_epochs: 20
num_gaussians_init: 3000
num_workers: 8
output_dT: 3.2e-11
output_dir: ./real_output/Swall3_E_manualz0_041801
output_res: 128
output_t_range:
- 0
- 512
output_wallsize: 1
predict_batch_size: 256
prune_lowthreshold: 0.008
prune_upthreshold: 0.075
render_magnification: 50000.0
save_interval: 20
scale_activation_mode: tanh
scale_factor: 0.001
scale_init: 0.01
scale_max: 0.015
scale_min: 0.005
seed: 0
simplified_amplitude_epochs: -1
split_threshold: 0.01
t_range:
- 0
- 350
train_split: 0.99
use_auto_wall: true
use_seed: true
virtual_wall_path: ./virtual_wall/humanwall_virtual_wall_128_1211.mat
warmup_ratio: 0.0
weight_decay: 1.0e-09
x_max: 0.5
x_min: -0.5
y_max: 0.5
y_min: -0.5
z_max: 0.9
z_min: 0.5
